---
name: Games-Perlwar
version: 0.02
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: |
  PerlWar is inspired by the classic Corewar game.
  In this game, players pit snippets of Perl code (called 'agents') 
  against each other in order to gain control of the vicious virtual
  battlefield known as... the Array.
license: perl
build_requires:
  Carp: 0
  Class::Std: 0
  Cwd: 0
  File::Copy: 0
  IO::File: 0
  IO::Prompt: 0
  Safe: 0
  XML::LibXML: 0
  XML::Simple: 0
  XML::Writer: 0
  version: 0
provides:
  Games::PerlWar:
    file: lib/Games/PerlWar.pm
    version: 0.02
  Games::PerlWar::AgentEval:
    file: lib/Games/PerlWar/AgentEval.pm
    version: v0.2.0
  Games::PerlWar::Array:
    file: lib/Games/PerlWar/Array.pm
    version: v0.2.0
  Games::PerlWar::Cell:
    file: lib/Games/PerlWar/Cell.pm
    version: v0.2.0
  Games::PerlWar::Shell:
    file: lib/Games/PerlWar/Shell.pm
    version: v0.2.0
generated_by: Module::Build version 0.2612
